os:
  - windows

language: c

before_install:
    - |
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain bison flex
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
    - git clone -b REL_14_STABLE --single-branch --depth 1 https://github.com/postgres/postgres.git
    - sed 's/\t/ /g' -i postgres/src/backend/storage/lmgr/lwlocknames.txt
    - cd postgres/src/tools/msvc
    - cp config_default.pl config.pl
    - ./build.bat

before_cache:
    - |-
        case $TRAVIS_OS_NAME in
          windows)
            # https://unix.stackexchange.com/a/137322/107554
            $msys2 pacman --sync --clean --noconfirm
            ;;
        esac

install:
    - echo 1

script:
    - echo 1

# Default MODE is basic, i.e. all tests with PG_PROBACKUP_TEST_BASIC=ON
env:
    - PG_VERSION=15 PG_BRANCH=master PTRACK_PATCH_PG_BRANCH=master

jobs:
    allow_failures:
        - if: env(PG_BRANCH) = master
        - if: env(PG_BRANCH) = REL9_5_STABLE
#        - if: env(MODE) IN (archive, backup, delta, locking, merge, replica, retention, restore)
