os: linux

dist: bionic

language: c

services:
    - docker

before_install:
    - cp travis/* .

install:
    - ./make_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run tests
    # - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests
    # - docker run -v $(pwd):/tests --rm centos:7 /tests/travis/backup_restore.sh

notifications:
    email:
        on_success: change
        on_failure: always

# Default MODE is basic, i.e. all tests with PG_PROBACKUP_TEST_BASIC=ON
env:
#    - PG_VERSION=15 PG_BRANCH=master PTRACK_PATCH_PG_VERSION=13
#    - PG_VERSION=14 PG_BRANCH=REL_14_STABLE PTRACK_PATCH_PG_VERSION=13
    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=auth_test OLD_BIN=off
    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=archive OLD_BIN=off
    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=backup OLD_BIN=2.4.10
    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=compatibility OLD_BIN=2.4.10
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=checkdb OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=config OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=compression OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=delete OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=delta OLD_BIN=2.4.10
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=exclude OLD_BIN=2.4.10
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=external OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=init OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=incr_restore OLD_BIN=2.4.10
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=locking OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=logging OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=merge OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=option OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=page OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=pgpro560 OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=pgpro589 OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=pgpro2068 OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=remote OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=replica OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=restore OLD_BIN=2.4.10
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=retention OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=set_backup OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=off MODE=show OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=snapfs OLD_BIN=off
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=time_stamp OLD_BIN=2.4.10
#    - PG_VERSION=13 PG_BRANCH=REL_13_STABLE PTRACK_PATCH_PG_VERSION=13 MODE=validate OLD_BIN=off

#    - PG_VERSION=9.6 PG_BRANCH=REL9_6_STABLE
#    - PG_VERSION=9.5 PG_BRANCH=REL9_5_STABLE


jobs:
    allow_failures:
        - if: env(PG_BRANCH) = master
#        - if: env(MODE) IN (archive, backup, delta, locking, merge, replica, retention, restore)

# Only run CI for master branch commits to limit our travis usage
#branches:
#    only:
#    - master

