os:
  - windows

language: c

before_install:
    - git clone -b REL_14_STABLE --single-branch --depth 1 https://github.com/postgres/postgres.git
    - cd postgres\src\tools\msvc
    - cp config_default.pl) config.pl
    - .\build.bat

before_cache:
    - |-
        case $TRAVIS_OS_NAME in
          windows)
            # https://unix.stackexchange.com/a/137322/107554
            $msys2 pacman --sync --clean --noconfirm
            ;;
        esac

install:
    - echo 1

script:
    - echo 1

# Default MODE is basic, i.e. all tests with PG_PROBACKUP_TEST_BASIC=ON
env:
    - PG_VERSION=15 PG_BRANCH=master PTRACK_PATCH_PG_BRANCH=master

jobs:
    allow_failures:
        - if: env(PG_BRANCH) = master
        - if: env(PG_BRANCH) = REL9_5_STABLE
#        - if: env(MODE) IN (archive, backup, delta, locking, merge, replica, retention, restore)
